apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
#- name: ghcr.io/KubeHatesMe/edu12-backend
#  newTag: "20230322092639"
images:
- name: ghcr.io/kubehatesme/edu12-backend
  newTag: "20230331072223"
